### ISSUE TITLE
In the Callback I was trying to disable the camera since the picture was taken. Intially i got an an error that said navigator.getUserMedia expects 3 parameters and i fixed that. The problem is I dont understand why Camera Access should show up even while disabling the camera

### ISSUE THREAD

**Issue by achands** [onemightyroar/angular-camera#15]

**Comment by achands** [comment]
I meant Camera Access Dialog*

**Comment by zachdunn** [comment]
As far as I remember, anytime you want to access and edit that userMedia attribute requires permission whenever you are on a non-SSL connection. The browser doesn't know what the intent is, just that the attribute is being accessed.

**Comment by squix78** [comment]
I also get that error. Do you mind to explain how you fixed it?

**Comment by panurge-ws** [comment]
It's not fixed.
How to replicate:

```
set enabled="false"
```

How to fix in the directive, replace the function in scope.disabelCamera, with:

```
scope.disableCamera = function () {
        if (scope.stream){
          scope.stream.stop();
        }
      };
```
