### ISSUE TITLE
Taking picture yields completely black photo

### ISSUE THREAD

**Issue by JuneKelly** [onemightyroar/angular-camera#5]
I've started a project using angular camera: https://github.com/ShaneKilkelly/snaply

The camera is set up like so:

```
<ng-camera
      type="photo"
      enabled="true"
      width="400"
      countdown="3"
      ng-model="media"
      capture-message="Go!"></ng-camera>
```

The webcam image appears on the page as expected.

When "take a picture is clicked", the result is that $scope.media is set to a base64 encoded string of a completely black image. No errors are shown in the js console.

When the image is either rendered in an img tag (`<img src="{{media}}" />`), or opened in a new tab, it appears as a completely black rectangle.

The base64 string generated is in this gist: https://gist.github.com/ShaneKilkelly/7975159

Tested on Chrome 31.0.1650.63, Ubuntu 13.10, Angular version 1.2.4

**Comment by zachdunn** [comment]
Hey Shane,

Add in a default height and you should be good.

Without a defined size, it seems like the rendered image becomes a black rectangle. I'd also recommend you change your image to use ng-src instead of src since it's bound to the scope.

**Comment by JuneKelly** [comment]
Hi Zach,

Thanks, setting both a width and height did indeed solve the problem.
I think I had left the height off because the video could then scale to whatever aspect ratio the camera could use, rather than specifying the ration up front.
